<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>1.4.0</Version>
    <Company>FileHound</Company>
    <Product>FileHound</Product>
  </PropertyGroup>
</Project>
