<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>FileHound</AssemblyName>
    <RootNamespace>FileHound.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <TieredPGO>true</TieredPGO>
    <ServerGarbageCollector>false</ServerGarbageCollector>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\*.png" />
    <Resource Include="Assets\app.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FileHound.Indexing\FileHound.Indexing.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="FileHound.App.Tests" />
    <Using Include="FileHound.Core.Index" />
    <Using Include="FileHound.Core.Search" />
    <Using Include="FileHound.Indexing" />
  </ItemGroup>
</Project>
