<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FileHound.Core.Index" />
    <Using Include="FileHound.Core.Query" />
    <Using Include="FileHound.Core.Matching" />
    <Using Include="FileHound.Core.Search" />
    <Using Include="System.Diagnostics" />
    <ProjectReference Include="..\..\src\FileHound.Core\FileHound.Core.csproj" />
  </ItemGroup>
</Project>
